-- Generated by Oracle SQL Developer Data Modeler 22.2.0.165.1149
--   at:        2023-05-21 19:01:15 CET
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



-- predefined type, no DDL - MDSYS.SDO_GEOMETRY

-- predefined type, no DDL - XMLTYPE

CREATE SEQUENCE championship_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE city_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE event_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE match_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE player_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE refree_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE team_id_seq START WITH 1 NOCACHE ORDER;

CREATE TABLE championship (
    id         INTEGER
        CONSTRAINT nnc_championship_id NOT NULL,
    date_debut DATE NOT NULL,
    date_fin   DATE NOT NULL,
    winner     INTEGER NOT NULL
)
LOGGING;

ALTER TABLE championship ADD CONSTRAINT championship_pk PRIMARY KEY ( id );

ALTER TABLE championship ADD CONSTRAINT championship__un UNIQUE ( date_debut,
                                                                  date_fin );

CREATE TABLE championship_match (
    championship_id INTEGER NOT NULL,
    match_id        INTEGER NOT NULL
)
LOGGING;

ALTER TABLE championship_match ADD CONSTRAINT championship_match_pk PRIMARY KEY ( championship_id,
                                                                                  match_id );

CREATE TABLE city (
    id          INTEGER
        CONSTRAINT nnc_city_id NOT NULL,
    name        CHAR(30),
    postal_code INTEGER
)
LOGGING;

ALTER TABLE city ADD CONSTRAINT city_pk PRIMARY KEY ( id );

CREATE TABLE event (
    id        INTEGER NOT NULL,
    player_id INTEGER NOT NULL,
    match_id  INTEGER NOT NULL,
    minute    DATE,
    half      INTEGER,
    kind      CHAR(40)
)
LOGGING;

ALTER TABLE event ADD CONSTRAINT event_pk PRIMARY KEY ( id );

CREATE TABLE match (
    id         INTEGER NOT NULL,
    date_match DATE,
    home_team  INTEGER NOT NULL,
    away_team  INTEGER NOT NULL,
    home_score INTEGER NOT NULL,
    away_score INTEGER NOT NULL
)
LOGGING;

ALTER TABLE match ADD CONSTRAINT match_pk PRIMARY KEY ( id );

CREATE TABLE match_day_squad (
    player_id INTEGER NOT NULL,
    match_id  INTEGER NOT NULL,
    team_id   INTEGER NOT NULL,
    kind      CHAR(30)
)
LOGGING;

ALTER TABLE match_day_squad ADD CONSTRAINT match_day_squad_pk PRIMARY KEY ( player_id,
                                                                            match_id );

CREATE TABLE match_refree (
    refree_id INTEGER NOT NULL,
    match_id  INTEGER NOT NULL
)
LOGGING;

ALTER TABLE match_refree ADD CONSTRAINT match_refree_pk PRIMARY KEY ( refree_id,
                                                                      match_id );

CREATE TABLE player (
    id         INTEGER NOT NULL,
    first_name CHAR(50),
    last_name  CHAR(50),
    nickname   INTEGER,
    birthday   DATE,
    position   CHAR(30),
    manager    CHAR(1),
    team_id    INTEGER
)
LOGGING;

ALTER TABLE player ADD CONSTRAINT player_pk PRIMARY KEY ( id );

CREATE TABLE refree (
    id   INTEGER NOT NULL,
    name CHAR(50),
    role CHAR(40) NOT NULL
)
LOGGING;

ALTER TABLE refree ADD CONSTRAINT refree_pk PRIMARY KEY ( id );

CREATE TABLE team (
    id              INTEGER NOT NULL,
    name            CHAR(40),
    city            INTEGER NOT NULL,
    championship_id INTEGER NOT NULL,
    city_id         INTEGER NOT NULL
)
LOGGING;

ALTER TABLE team ADD CONSTRAINT team_pk PRIMARY KEY ( id );

--  ERROR: FK name length exceeds maximum allowed length(30) 
ALTER TABLE championship_match
    ADD CONSTRAINT championship_match_championship_fk FOREIGN KEY ( championship_id )
        REFERENCES championship ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE championship_match
    ADD CONSTRAINT championship_match_match_fk FOREIGN KEY ( match_id )
        REFERENCES match ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE championship
    ADD CONSTRAINT championship_team_fk FOREIGN KEY ( winner )
        REFERENCES team ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE event
    ADD CONSTRAINT event_match_fk FOREIGN KEY ( match_id )
        REFERENCES match ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE event
    ADD CONSTRAINT event_player_fk FOREIGN KEY ( player_id )
        REFERENCES player ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE match_day_squad
    ADD CONSTRAINT match_day_squad_match_fk FOREIGN KEY ( match_id )
        REFERENCES match ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE match_day_squad
    ADD CONSTRAINT match_day_squad_player_fk FOREIGN KEY ( player_id )
        REFERENCES player ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE match_day_squad
    ADD CONSTRAINT match_day_squad_team_fk FOREIGN KEY ( team_id )
        REFERENCES team ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE match_refree
    ADD CONSTRAINT match_refree_match_fk FOREIGN KEY ( match_id )
        REFERENCES match ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE match_refree
    ADD CONSTRAINT match_refree_refree_fk FOREIGN KEY ( refree_id )
        REFERENCES refree ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE match
    ADD CONSTRAINT match_team_fk FOREIGN KEY ( home_team )
        REFERENCES team ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE match
    ADD CONSTRAINT match_team_fkv2 FOREIGN KEY ( away_team )
        REFERENCES team ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE player
    ADD CONSTRAINT player_team_fk FOREIGN KEY ( team_id )
        REFERENCES team ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE team
    ADD CONSTRAINT team_championship_fk FOREIGN KEY ( championship_id )
        REFERENCES championship ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

ALTER TABLE team
    ADD CONSTRAINT team_city_fk FOREIGN KEY ( city_id )
        REFERENCES city ( id )
            ON DELETE CASCADE
    NOT DEFERRABLE;

CREATE OR REPLACE TRIGGER championship_id_trg BEFORE
    INSERT ON championship
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := championship_id_seq.nextval;
END;
/

CREATE OR REPLACE TRIGGER city_id_trg BEFORE
    INSERT ON city
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := city_id_seq.nextval;
END;
/

CREATE OR REPLACE TRIGGER event_id_trg BEFORE
    INSERT ON event
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := event_id_seq.nextval;
END;
/

CREATE OR REPLACE TRIGGER match_id_trg BEFORE
    INSERT ON match
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := match_id_seq.nextval;
END;
/

CREATE OR REPLACE TRIGGER player_id_trg BEFORE
    INSERT ON player
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := player_id_seq.nextval;
END;
/

CREATE OR REPLACE TRIGGER refree_id_trg BEFORE
    INSERT ON refree
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := refree_id_seq.nextval;
END;
/

CREATE OR REPLACE TRIGGER team_id_trg BEFORE
    INSERT ON team
    FOR EACH ROW
    WHEN ( new.id IS NULL )
BEGIN
    :new.id := team_id_seq.nextval;
END;
/

CREATE OR REPLACE TRIGGER convert_yellow_to_red
BEFORE INSERT ON event
FOR EACH ROW
DECLARE
    yellow_card_count INTEGER;
BEGIN
    IF :new.kind = 'Yellow Card' THEN
        -- Get the count of yellow cards for the player in the match
        SELECT COUNT(*) INTO yellow_card_count
        FROM event
        WHERE player_id = :new.player_id
            AND match_id = :new.match_id
            AND kind = 'Yellow Card';
        
        

        IF yellow_card_count = 1 THEN
            DELETE FROM event
            WHERE player_id = :new.player_id
                AND match_id = :new.match_id
                AND kind = 'Yellow Card';

            -- Delete the first yellow card
            :new.kind := 'Red Card';
        END IF;
    END IF;
END;
/

-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            10
-- CREATE INDEX                             0
-- ALTER TABLE                             26
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           7
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          7
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   1
-- WARNINGS                                 0

